---
name: RevivalTax
api: 5.0.0
version: 0.0.2
depend: [EconomyAPI]
main: NhanAZ\RevivalTax\Main
website: https://github.com/NhanAZ
src-namespace-prefix: NhanAZ\RevivalTax
description: The player will be deducted the revival tax on death.
...
