---
# Percentage of tax amount deducted by player after revival
# The player's deducted amount is calculated using the formula below:
# (Player's Money) x TaxPercent(%) / 100 = (Player taxes are deducted when they revival)
taxPercent: 10 #Percent(%)

# Message sent to players when they death
# {taxMoney} : Server revival tax percentage
# {taxPercent} The amount of the player's revival tax to pay
taxMessage: "§aYou have been deducted §e{taxMoney} §arevival tax! §f(§bTax Percent: §c{taxPercent}%§f)§r"
...
